version: '3.8'

services:
  app:
    image: raphaelrsantos/imobia:latest
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - traefik-public
    labels:
      traefik.enable: "true"
      traefik.docker.network: "network_swarm_public"
      traefik.http.routers.imobia.rule: "Host(`imobia.chat`)"
      traefik.http.routers.imobia.entrypoints: "websecure"
      traefik.http.routers.imobia.tls.certresolver: "letsencryptresolver"
      traefik.http.services.imobia.loadbalancer.server.port: "8501"
    deploy:
      restart_policy:
        condition: on-failure

networks:
  traefik-public:
    external: true
    name: network_swarm_public