version: '3.8'

services:
  helena-app:
    image: raphaelrsantos/imobia:latest
    ports:
      - "8501:8501"
    environment:
      # A variável OPENAI_API_KEY será injetada pelo Portainer ou por um arquivo .env
      - OPENAI_API_KEY=${OPENAI_API_KEY}